#!/usr/bin/env python3
"""Deterministic generator for assets/models/lion_ball.glb (RB-027).

Writes a glTF 2.0 binary with only the Python stdlib so the mascot can be
regenerated byte-stably on any machine:

    python3 tools/generate_lion_asset.py

Node contract (game_root.gd wires expressions onto these names):
  LionBall
  ├── BallBody                 gold sphere, r = 0.25 m (matches the collider)
  ├── Mane                     tuft ring around the face axis (rig scales it)
  │   └── Tuft00..Tuft15
  ├── EarOuterL / EarOuterR    (rig pins them back while charging)
  ├── EarInnerL / EarInnerR
  └── FaceRoot
      ├── EyeWhiteL / EyeWhiteR
      ├── PupilL / PupilR      (rig blinks by scaling y; catchlights attach)
      ├── Muzzle
      └── Nose

Face looks down +Z, units are meters, origin is the ball center — identical
frame to the legacy scene primitives it replaces.

License: CC0-1.0 (authored for this project; no third-party assets).
"""

import json
import math
import os
import struct

OUT_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "assets", "models", "lion_ball.glb"
)

# Palette (matches the shipped procedural mascot so tuning carries over).
GOLD = [0.91, 0.64, 0.24, 1.0]        # body
MANE = [0.79, 0.44, 0.12, 1.0]        # mane tufts
EAR_OUTER = [0.87, 0.60, 0.20, 1.0]   # ear outer
CREAM = [0.97, 0.89, 0.76, 1.0]       # ear inner, muzzle
SCLERA = [0.98, 0.98, 0.97, 1.0]      # eye whites
DARK = [0.16, 0.12, 0.10, 1.0]        # pupils, nose


def sphere(radius, seg_u, seg_v, scale=(1.0, 1.0, 1.0)):
    """UV sphere → (positions, normals, indices). Ellipsoid normals are the
    analytically correct gradient directions."""
    sx, sy, sz = scale
    verts, norms = [], []
    for v in range(seg_v + 1):
        phi = math.pi * v / seg_v
        for u in range(seg_u + 1):
            theta = 2.0 * math.pi * u / seg_u
            nx = math.sin(phi) * math.cos(theta)
            ny = math.cos(phi)
            nz = math.sin(phi) * math.sin(theta)
            verts.append((nx * radius * sx, ny * radius * sy, nz * radius * sz))
            g = (nx / max(sx, 1e-6), ny / max(sy, 1e-6), nz / max(sz, 1e-6))
            gl = math.sqrt(g[0] * g[0] + g[1] * g[1] + g[2] * g[2])
            norms.append((g[0] / gl, g[1] / gl, g[2] / gl))
    idx = []
    for v in range(seg_v):
        for u in range(seg_u):
            a = v * (seg_u + 1) + u
            b = a + 1
            c = a + seg_u + 1
            d = c + 1
            if v == 0:
                idx += [a, c, d]
            elif v == seg_v - 1:
                idx += [a, c, b]
            else:
                idx += [a, c, b, b, c, d]
    return verts, norms, idx


def cone(radius, height, radial):
    """Cone with apex up (+Y), base ring open (tuft silhouette only)."""
    verts, norms, idx = [], [], []
    apex = len(verts)
    verts.append((0.0, height * 0.5, 0.0))
    norms.append((0.0, 1.0, 0.0))
    ring = len(verts)
    slope = radius / max(height, 1e-6)
    for i in range(radial):
        theta = 2.0 * math.pi * i / radial
        x, z = math.cos(theta) * radius, math.sin(theta) * radius
        verts.append((x, -height * 0.5, z))
        g = math.sqrt(1.0 + slope * slope)
        norms.append((math.cos(theta) / g, slope / g, math.sin(theta) / g))
    for i in range(radial):
        idx += [apex, ring + i, ring + (i + 1) % radial]
    return verts, norms, idx


def quat_from_to(a, b):
    """Quaternion rotating unit vector a onto unit vector b (x, y, z, w)."""
    ax, ay, az = a
    bx, by, bz = b
    d = ax * bx + ay * by + az * bz
    if d < -0.999999:
        # Opposite: rotate 180° about any orthogonal axis.
        axis = (1.0, 0.0, 0.0) if abs(ay) < 0.9 else (0.0, 1.0, 0.0)
        x, y, z = _cross(axis, a)
        n = math.sqrt(x * x + y * y + z * z)
        return [x / n, y / n, z / n, 0.0]
    x, y, z = _cross(a, b)
    w = 1.0 + d
    n = math.sqrt(x * x + y * y + z * z + w * w)
    return [x / n, y / n, z / n, w / n]


def _cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def _normalized(v):
    n = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
    return (v[0] / n, v[1] / n, v[2] / n)


class Gltf:
    def __init__(self):
        self.bin = bytearray()
        self.views = []
        self.accessors = []
        self.meshes = []
        self.materials = []

    def _align(self):
        while len(self.bin) % 4:
            self.bin.append(0)

    def _view(self, data, target):
        self._align()
        offset = len(self.bin)
        self.bin += data
        self.views.append(
            {"buffer": 0, "byteOffset": offset, "byteLength": len(data), "target": target}
        )
        return len(self.views) - 1

    def add_material(self, base_color, roughness):
        self.materials.append(
            {
                "pbrMetallicRoughness": {
                    "baseColorFactor": base_color,
                    "metallicFactor": 0.0,
                    "roughnessFactor": roughness,
                },
                "doubleSided": False,
            }
        )
        return len(self.materials) - 1

    def add_mesh(self, verts, norms, idx, material):
        vdata = b"".join(struct.pack("<3f", *p) for p in verts)
        ndata = b"".join(struct.pack("<3f", *n) for n in norms)
        idata = b"".join(struct.pack("<H", i) for i in idx)
        vview = self._view(vdata, 34962)
        nview = self._view(ndata, 34962)
        iview = self._view(idata, 34963)
        pos_acc = len(self.accessors)
        self.accessors.append(
            {
                "bufferView": vview,
                "componentType": 5126,
                "count": len(verts),
                "type": "VEC3",
                "min": [min(p[i] for p in verts) for i in range(3)],
                "max": [max(p[i] for p in verts) for i in range(3)],
            }
        )
        nrm_acc = len(self.accessors)
        self.accessors.append(
            {"bufferView": nview, "componentType": 5126, "count": len(norms), "type": "VEC3"}
        )
        idx_acc = len(self.accessors)
        self.accessors.append(
            {"bufferView": iview, "componentType": 5123, "count": len(idx), "type": "SCALAR"}
        )
        self.meshes.append(
            {
                "primitives": [
                    {
                        "attributes": {"POSITION": pos_acc, "NORMAL": nrm_acc},
                        "indices": idx_acc,
                        "material": material,
                        "mode": 4,
                    }
                ]
            }
        )
        return len(self.meshes) - 1, len(idx) // 3


def build():
    g = Gltf()
    tri_total = 0
    mesh_info = {}

    def add(name, geo, color, roughness):
        nonlocal tri_total
        mat = g.add_material(color, roughness)
        mesh, tris = g.add_mesh(*geo, mat)
        mesh_info[name] = (mesh, tris)
        tri_total += tris
        return mesh

    add("BallBody", sphere(0.25, 26, 18), GOLD, 0.55)
    tuft_mesh = add("Tuft", cone(0.075, 0.24, 8), MANE, 0.65)
    add("EarOuter", sphere(0.068, 12, 9, (1.0, 1.15, 0.6)), EAR_OUTER, 0.6)
    add("EarInner", sphere(0.042, 10, 7, (1.0, 1.0, 0.5)), CREAM, 0.7)
    add("EyeWhite", sphere(0.072, 12, 9), SCLERA, 0.35)
    add("Pupil", sphere(0.052, 12, 9), DARK, 0.3)
    add("Muzzle", sphere(0.085, 14, 10, (1.15, 0.9, 0.8)), CREAM, 0.7)
    add("Nose", sphere(0.045, 10, 7, (1.25, 0.8, 0.7)), DARK, 0.3)

    # Node layout: 0 root, 1 body, 2 mane, 3..6 ears, 7 face root,
    # 8..43 mane tufts (two rings), 44..49 face parts.
    nodes = [
        {"name": "LionBall", "children": [1, 2, 3, 4, 5, 6, 7]},
        {"name": "BallBody", "mesh": mesh_info["BallBody"][0]},
        {"name": "Mane", "children": []},
        _mesh_node("EarOuterL", "EarOuter", (-0.175, 0.20, 0.04), mesh_info),
        _mesh_node("EarOuterR", "EarOuter", (0.175, 0.20, 0.04), mesh_info),
        _mesh_node("EarInnerL", "EarInner", (-0.175, 0.20, 0.072), mesh_info),
        _mesh_node("EarInnerR", "EarInner", (0.175, 0.20, 0.072), mesh_info),
        {"name": "FaceRoot", "children": []},
    ]

    # Mane: two staggered rings around the face (+Z) axis. Tufts point
    # outward, slightly up, and lean back off the face; alternating lengths
    # give the silhouette a hand-drawn feel. 20 outer + 14 inner tufts fully
    # ring the face so the gold body never reads through.
    for ring_idx, (count, ring_r, base_z, scale_mult) in enumerate(
        [(20, 0.225, 0.12, 1.0), (14, 0.16, 0.17, 0.7)]
    ):
        for i in range(count):
            theta = 2.0 * math.pi * i / count
            offset = (math.pi / count) if ring_idx == 1 else 0.0
            theta += offset
            radial = (math.cos(theta), 0.0, math.sin(theta))
            px, pz = radial[0] * ring_r, radial[2] * ring_r
            py = 0.03 + 0.02 * math.cos(2 * theta)
            scale = (1.0 + (0.25 if i % 2 == 0 else 0.0) - 0.15 * abs(math.sin(theta))) * scale_mult
            direction = _normalized((radial[0], 0.45, radial[2] - 0.25))
            nodes.append(
                {
                    "name": "Tuft%d_%02d" % (ring_idx, i),
                    "mesh": tuft_mesh,
                    "translation": [px, py, base_z],
                    "rotation": quat_from_to((0.0, 1.0, 0.0), direction),
                    "scale": [scale, scale, scale],
                }
            )
            nodes[2]["children"].append(len(nodes) - 1)

    face_parts = [
        _mesh_node("EyeWhiteL", "EyeWhite", (-0.082, 0.082, 0.185), mesh_info),
        _mesh_node("EyeWhiteR", "EyeWhite", (0.082, 0.082, 0.185), mesh_info),
        _mesh_node("PupilL", "Pupil", (-0.075, 0.075, 0.242), mesh_info),
        _mesh_node("PupilR", "Pupil", (0.075, 0.075, 0.242), mesh_info),
        _mesh_node("Muzzle", "Muzzle", (0.0, -0.05, 0.21), mesh_info),
        _mesh_node("Nose", "Nose", (0.0, -0.012, 0.285), mesh_info),
    ]
    for part in face_parts:
        nodes.append(part)
        nodes[7]["children"].append(len(nodes) - 1)

    gltf = {
        "asset": {
            "version": "2.0",
            "generator": "roar3d tools/generate_lion_asset.py (stdlib, deterministic)",
        },
        "scene": 0,
        "scenes": [{"name": "Scene", "nodes": [0]}],
        "nodes": nodes,
        "meshes": g.meshes,
        "materials": g.materials,
        "accessors": g.accessors,
        "bufferViews": g.views,
        "buffers": [{"byteLength": len(g.bin)}],
    }

    js = json.dumps(gltf, separators=(",", ":")).encode("utf-8")
    while len(js) % 4:
        js += b" "
    g._align()

    out = struct.pack("<III", 0x46546C67, 2, 12 + 8 + len(js) + 8 + len(g.bin))
    out += struct.pack("<II", len(js), 0x4E4F534A) + js
    out += struct.pack("<II", len(g.bin), 0x004E4942) + bytes(g.bin)

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "wb") as f:
        f.write(out)

    print("wrote %s (%d bytes)" % (os.path.abspath(OUT_PATH), len(out)))
    for name, (_, tris) in sorted(mesh_info.items()):
        print("  %-10s %5d tris" % (name, tris))
    print("materials: %d" % len(g.materials))
    # Instanced meshes count once in the file; the scene instances them.
    tuft_tris = mesh_info["Tuft"][1]
    total = tri_total + 15 * tuft_tris
    print("rendered triangles: %d (16 tuft instances)" % total)


def _mesh_node(name, mesh_name, translation, mesh_info):
    return {
        "name": name,
        "mesh": mesh_info[mesh_name][0],
        "translation": list(translation),
    }


if __name__ == "__main__":
    build()
